# Phase 3A formal spec text (verbatim). Used by edit_phase3a_spec.py.
# No timestamps, no random IDs, deterministic.

MANUAL_SECTION_TITLE = "Phase 3A — Pressure Eligibility and Diffusion (Design Freeze)"

MANUAL_SPEC_BODY = r"""
Phase 3A — Pressure Eligibility and Diffusion
Formal Specification (Design Freeze)

1. Purpose and Scope

Phase 3A introduces pressure propagation mechanics that transform static spatial relationships into actionable interaction without resolving combat, collapse, or negotiation.

This phase exists to:
- make settlement adjacency and contact geometry operational,
- constrain pressure flow through spatial, structural, and state-based eligibility,
- redistribute accumulated pressure deterministically and conservatively.

Phase 3A does not tune gameplay outcomes and does not introduce negative-sum effects by itself.

2. Conceptual Definition

Pressure represents accumulated coercive stress generated by sustained military presence, posture, and contact. Pressure is not damage, not attrition, and not exhaustion.

Phase 3A governs how existing pressure spreads, not how pressure is created or resolved.

3. Canonical Inputs (Locked)

Phase 3A operates exclusively on previously derived spatial artifacts.

3.1 Settlement Substrate
Authoritative geometry source:
data/derived/settlements_substrate.geojson

No snapping, repair, inferred borders, or geometry invention is permitted.

3.2 Contact Graph (Phase 1)
data/derived/settlement_contact_graph.json

Typed contacts:
- shared_border
- point_touch
- distance_contact

3.3 Enriched Contact Graph (Phase 2)
data/derived/settlement_contact_graph_enriched.json

Additional metrics include:
- centroid_distance_svg
- contact_span_svg
- bbox_overlap_ratio
- area_ratio
- perimeter_ratio

Phase 3A may only reference these metrics. No pruning or reclassification is permitted.

4. Phase 3A.1 — Pressure Eligibility

4.1 Purpose

Eligibility determines whether and how strongly pressure may propagate across a given settlement contact edge.

Eligibility does not apply pressure. It constrains future diffusion.

4.2 Hard Gating Conditions

An edge is ineligible if any of the following conditions are met:

- Source or destination settlement is in exhaustion collapse
- Cohesion failure invalidates coordinated pressure
- Structural integrity constraints are violated

Hard gates are absolute. An ineligible edge has effective weight = 0.

4.3 Weight Computation

For eligible edges, an effective weight w ∈ [0,1] is computed deterministically:

w = base(contact_type) × f_distance × f_shape × f_state × f_posture

Where:
- base(contact_type) is fixed per contact class
- f_distance derives from centroid and span metrics
- f_shape derives from geometric ratios
- f_state reflects settlement state constraints
- f_posture reflects formation posture interaction

No term may exceed 1. No negative weights are permitted.

Weights are advisory multipliers, not probabilities.

4.4 Output

Phase 3A.1 produces:
- an effective in-memory edge list,
- a deterministic audit summary,
- no persistent state changes.

Eligibility is feature-gated and default-off until explicitly enabled.

5. Phase 3A.2 — Pressure Diffusion

5.1 Purpose

Diffusion redistributes existing pressure across eligible edges in a bounded and conservative manner.

Diffusion:
- smooths local pressure imbalances,
- delays propagation across weak links,
- preserves total pressure mass.

Diffusion does not create exhaustion, collapse, or territorial change.

5.2 Canonical Pressure Field

The authoritative pressure field is:
state.front_pressure

Pressure is edge-keyed. Node pressure is derived deterministically for analysis only.

5.3 Diffusion Rules (Frozen)

Diffusion obeys the following invariants:

- Conservative: total pressure is preserved globally
- Bounded: per-node outflow is capped
- Deterministic: stable ordering and rounding fixes enforced
- Local: diffusion magnitude is proportional to eligibility weight

Fixed constants:
DIFFUSE_FRACTION = 0.05
DIFFUSE_MAX_OUTFLOW = 2.0
DIFFUSE_EPS = 1e-9

Constants are conservative by design and not gameplay tuning knobs.

5.4 Execution Conditions

Diffusion runs only if:
- Phase 3A eligibility is enabled, and
- Phase 3A diffusion is enabled.

Diffusion runs:
- after eligibility computation,
- before militia fatigue and later systems,
- without persistence or geometry writes.

5.5 Output Contract

Diffusion returns a structured result:

{
  applied: boolean,
  reason_if_not_applied: string,
  stats: {
    nodes_with_outflow,
    total_outflow,
    total_inflow,
    conserved_error_fix_applied
  }
}

Any namespace or determinism violation aborts execution.

6. Determinism and Auditability

Phase 3A enforces:
- no randomness,
- no timestamps,
- stable ordering of all collections,
- byte-identical outputs across reruns.

All validation harness outputs are canonical and hash-tracked.

7. Design Constraints (Explicit)

Phase 3A does not:
- dissipate pressure,
- generate exhaustion,
- trigger collapse,
- influence negotiation directly,
- expose UI elements,
- provide AI heuristics.

Any such effects must be introduced in later phases.

8. Canonical Interpretation

Pressure diffusion represents the spatial equilibration of coercive stress across eligible contacts. It delays escalation across weak links and smooths local imbalances without producing loss, exhaustion, or decisive outcomes. Diffusion is a structural substrate upon which negative-sum dynamics are later imposed.

This statement is binding.

9. Freeze Status

Phase 3A eligibility and diffusion are design-frozen.

Any future modification requires:
- explicit phase advancement,
- ledger entry,
- justification against canon invariants.
"""

RULEBOOK_SUBSECTION_TITLE = "Phase 3A — Pressure eligibility and diffusion"

RULEBOOK_SUBSECTION_BODY = (
    "Phase 3A allows pressure to propagate across settlement contacts using deterministic "
    "eligibility weights derived only from Phase 2 contact metrics. Each turn, eligible pressure "
    "diffuses conservatively across those contacts, smoothing local imbalances and delaying "
    "propagation across weak links without creating or destroying pressure. Diffusion is a "
    "structural substrate only: it does not itself cause exhaustion, collapse, territorial change, "
    "or negotiation effects. The formal frozen specification is defined in the Systems & Mechanics "
    "Manual under \"Phase 3A — Pressure Eligibility and Diffusion (Design Freeze)\"."
)
