# Phase 3B formal spec text (verbatim). Used by edit_phase3b_spec.py.
# No timestamps, no random IDs, deterministic.

MANUAL_SECTION_TITLE = "Phase 3B — Pressure → Exhaustion Coupling (Design Freeze)"

MANUAL_SPEC_BODY = r"""
Phase 3B — Pressure → Exhaustion Coupling
Formal Specification (Design Freeze)

1. Purpose and Scope

Phase 3B introduces the first negative-sum transformation in the pressure system by coupling sustained pressure to irreversible exhaustion.

This phase exists to:
- convert persistent coercive pressure into strategic cost,
- enforce the negative-sum nature of prolonged conflict,
- narrow future options without causing immediate collapse or territorial change.

Phase 3B does not resolve combat, force collapse, or trigger negotiation directly.

2. Conceptual Definition

Exhaustion represents cumulative, irreversible military, political, and societal strain.

Phase 3B defines how pressure becomes costly over time.

Pressure remains conservative during diffusion (Phase 3A) and non-decisive on its own.

Exhaustion is the sink through which pressure imposes long-term consequences.

3. Canonical Inputs (Locked)

Phase 3B operates exclusively on:
- state.front_pressure (edge-keyed, canonical),
- settlement and formation state variables already defined in prior phases,
- derived contact eligibility from Phase 3A.

No new spatial artifacts, metrics, or geometry are introduced.

4. Coupling Model Overview

4.1 Structural Position in Turn Order

Pressure → exhaustion coupling executes:
- after Phase 3A pressure diffusion,
- before collapse resolution, negotiation checks, or political effects,
- once per turn.

Coupling reads pressure; it does not modify pressure values.

4.2 Unit of Accounting (Frozen)

Exhaustion coupling is edge-based, derived from:
- edge pressure magnitude,
- edge persistence over time,
- local state modifiers.

Node-derived or aggregate pressure is not used directly.

5. Eligibility for Exhaustion Generation

5.1 Persistence Gate (Hard)

Pressure must exceed a minimal significance threshold for N consecutive turns.
- One-turn pressure spikes are ignored.
- Persistence counters reset if pressure drops below threshold.

5.2 State Gating (Hard)

At least one of the following must apply on or across the edge:
- static or semi-static front contact,
- brittle or Cut supply dependency,
- enclave-like isolation or integrity decline,
- prolonged contested control without consolidation.

Edges in fluid maneuver or early-contact states do not generate exhaustion.

5.3 Integrity Gating (Hard)

If either side on the edge is already in:
- exhaustion collapse, or
- total authority failure,

additional exhaustion from that edge is suppressed.

6. Exhaustion Accrual Rules

6.1 Accrual Characteristics (Frozen)

Exhaustion accrual is:
- monotonic,
- irreversible,
- bounded per turn,
- proportional rather than threshold-triggered.

No exhaustion spike may occur in a single turn.

6.2 Allocation Targets

Exhaustion generated by an edge is allocated to:
- formations exerting or absorbing pressure, and/or
- affected settlements or municipal control zones,

according to existing exhaustion attribution rules.

No new exhaustion categories are introduced.

6.3 Caps and Safeguards

Per-edge and per-turn exhaustion contribution is capped.

Global exhaustion growth per faction per turn is also capped to ensure gradual degradation and numerical stability.

7. Non-Effects (Explicit)

Phase 3B does not:
- reduce or dissipate pressure,
- alter diffusion behavior,
- directly cause control flips,
- directly trigger fragmentation,
- directly open negotiation windows,
- modify AI behavior.

8. Determinism and Auditability

Phase 3B enforces:
- deterministic edge evaluation ordering,
- stable persistence counters,
- no randomness,
- no timestamps,
- reproducible exhaustion deltas per turn.

9. Canonical Interpretation (Binding)

Sustained coercive pressure imposes irreversible strategic cost. Pressure that persists under constrained, static, or degraded conditions converts gradually into exhaustion, narrowing future options without producing immediate collapse or decisive outcomes. Exhaustion, not pressure itself, remains the primary driver of war termination.

10. Freeze Status

Phase 3B pressure → exhaustion coupling is design-frozen.

Any future modification requires:
- explicit phase advancement,
- ledger entry,
- justification against exhaustion and determinism invariants.
"""

RULEBOOK_SUBSECTION_TITLE = "Phase 3B — Pressure and exhaustion"

RULEBOOK_SUBSECTION_BODY = (
    "Sustained pressure does not resolve the war directly. When pressure persists under static, "
    "constrained, or degraded conditions, it gradually converts into irreversible exhaustion. This "
    "coupling enforces the negative-sum nature of the conflict by narrowing future options rather than "
    "producing immediate collapse or territorial change. Exhaustion, not pressure itself, drives "
    "breakdown, negotiation, and war termination. The formal frozen specification for this mechanism "
    "is defined in the Systems & Mechanics Manual under \"Phase 3B — Pressure → Exhaustion Coupling "
    "(Design Freeze)\"."
)
